server.port: 3000
spring.datasource.username: "root"
spring.datasource.password: "abc123456"
spring.datasource.url: "jdbc:mysql://localhost:3306/CodeDetective?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8"
jwt:
  header: "Authorization"
  ttl: 1209600
  secret: "abcdqwerasdfpoiuuzxcvlkjhdfghyuohahahahacaonimaaooooaaaabbbbcccc56786666++++++++++++++++++++++++"
oss:
  endpoint: "oss-cn-beijing.aliyuncs.com"
  region: "cn-beijing"
  accessUsername: "ossUser@1863352413516545.onaliyun.com"
  bucketName: "code-detective-bucket"
  accessKeyId: "LTAI5t7gsqQb3eBXPrEAQrmS"
  accessKeySecret: "ZNj5zZNKna1NpJjYgGyY7LyBUxALI8"
  codeDir: "CodeRepositories/"

