server.port: 3000
spring.datasource.username: "root"
spring.datasource.password: "abc123456"
spring.datasource.url: "jdbc:mysql://localhost:3306/CodeDetective?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8"
jwt:
  header: "Authorization"
  ttl: 1209600
  secret: "abcdqwerasdfpoiuuzxcvlkjhdfghyuohahahahacaonimaaooooaaaabbbbcccc56786666++++++++++++++++++++++++"
